<?php

/**
 * no admin, very simple data release policy page
 *
 * one form, agree -> goto data download page, otherwise, to home page 
 */

require_once "tripal_data_release.inc";

/**
 * Implement hook_menu()
 */
function tripal_data_release_menu() {

  $items['tripal/datarelease'] = array(
    'title' => 'Cucurbita maxima Genome Data Release Policy',
    'description' => 'Cucurbita maxima Genome Data Release Policy.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_data_release_policy_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

